{
  "initialize": null,
  "scenario":
  {
    "time_period": "test_day",
    "electricity_price": "dynamic"
  },
  "step": 300,
  "length": 1728000,

  "controller":
  {
    "name": "examples.python.controllers.pid",
    "use_forecast": false,
    "u":
    {
        "oveAct_u": 0,
        "oveAct_activate": 1
    }
  }

}